### PR TITLE
fixes #81 - checkpoints on transparent blocks

### LINKED ISSUE #81: Checkpoints on transparent blocks
If you attempt to create a checkpoint on a transparent block, for example GLASS, ICE, GLOWSTONE, STAIRS or ANVIL,  the checkpoint is created in the config files, but the pressure plate isn't (can't be) placed on these blocks. So the resulting course has a checkpoint that can never be reached.

Some transparent blocks, for example FENCE and WALL will allow the pressure plate to be placed but don't trigger the checkpoint when you step on it during a game.

Creating a checkpoint on a TNT block will blow a crater in your nice new course.

Some transparent blocks work without problems such as REDSTONE_BLOCK, REDSTONE_ORE, SLIME_BLOCK, PISTON, FURNACE, SLAB (upper), STAIRS (inverted).

Some transparent blocks get replaced by the pressure plate but still function correctly as a checkpoint in-game, e.g. CHEST, CAKE, BED, RAIL, SLAB (lower) .

### PR DESCRIPTION
**Pull request by steve4744**
Hi Ash, the detail is in #81 I guess.  I think there should be some sort of check that the block under the player can take a pressure plate before the checkpoint is added to the config files, otherwise the course becomes corrupt if the pressure plate fails to be created.

To begin with I thought there were only a few blocks affected but more kept appearing so ended up adding an enum class.

There is a "Material.isTransparent()" method which would make it simpler to check but quite a few of the blocks work normally as checkpoints so they would either be disallowed as checkpoints or potentially need to be allowed some other way.

### CODE REVIEW

**Comment by steve4744** [comment]
Rewritten without the need for enum class. I think it works much better now.

**Comment by A5H73Y** [comment]
Hey Steve, great work.
One suggestion would be to make this configurable, and enabled by default. Something like "Other.EnforceSafeCheckpoints", idk think of something obvious?
Also, move the logic you've done to check for an invalid placement into the Utils that returns a boolean of is valid, then just call that from the CheckpointMethods, and prevent the checkpoint if it isn't valid etc.

**Comment by A5H73Y** [comment]
Great work Steve! :)

**Comment by steve4744** [comment]
Thanks :-)

**Pull request merged**
