### PR TITLE
tabcomplete stuff

### PR DESCRIPTION
**Pull request by EOT3000**
This is to show that if you write h , then cmds shouldn't pop-up, because cmds doesn't start with h

### CODE REVIEW

**Comment by steve4744** [comment]
But it doesn't ?

**Comment by EOT3000** [comment]
sometimes it breaks

**Comment by steve4744** [comment]
Ok, I see what you mean, but its not really broken. I coded it so that if you type an invalid option it displays _all_ the valid options available to you. So instead of an emtpy list it returns all options:

```return auto.isEmpty() ? new ArrayList<>(list) : new ArrayList<>(auto);```

The default Mojang/Spigot response if you type an invalid option to a native command is to _remove_ all the options. So in your example when you type 'ba', no options are displayed.

This result can be achieved simply by changing the return statement to:

```return new ArrayList<>(auto);```

Not sure which I prefer to be honest, both have have their advantages/disadvantages.

**Comment by EOT3000** [comment]
oh

**Comment by A5H73Y** [comment]
Yeah I'd have to agree on Steve for this one, if a user has entered a command wrong they shouldn't be punished and left without an indication of how they should correct themselves.
Thank you for contributing to the plugin though, I appreciate it.

**Pull request closed without merging**
