### PR TITLE
fixes right-click interaction

### PR DESCRIPTION
**Pull request by steve4744**
Hi Ash,
I was looking at the issue regarding right click interaction with chests, crafting tables etc. that mibby raised. The change cancels the right click event when OnCourse.SneakToInteract is false, i.e. a normal right-click gets cancelled during the game. Clicking a 'leave' sign still works.

It does fix the problem, but I'd prefer you to check the logic of doing that.
Thanks,
Steve

### CODE REVIEW

**Comment by A5H73Y** [comment]
Hey Steve, thanks for looking to these for me! Haven't got the time I used to to look into these, so I do appreciate it!
Having looked at the logic so far, for the sake of DRY, you could put the isSneaking check after the event.setCancelled(true).

Also this is a PlayerInteractEvent, which I think covers a massive range of events, I don't know if there would be any major implication of cancelling it? For example do the pressureplates still work, do buttons / redstone still work, etc.

Without testing this in game I'm not sure. If you could disprove my suspicion and make sure it works fine then I'll pull the change.
Thanks again

**Comment by steve4744** [comment]
Yes, you are right - buttons didn't work the way it was. However....I've reworked it a bit and tested pressure plates, buttons, redstone and all seem to work ok.

The only situation where there might be an small issue is:

where sneak is enabled in the config and you right-click (without sneaking) while holding one of the items. It needs to be cancelled because you want to stop the sapling being planted in dirt for example. Downside is if you right-click a button while holding an item nothing will happen - needs to be with empty hand.

I also added a check for chests/furnaces/workbenches etc.

**Comment by steve4744** [comment]
I'm happy this works now.  Right click anywhere with a parkour item and it is actioned (e.g.leave course). Tested buttons, pressure plates and with/without 'sneak' enabled.

It also fixes part of issue 44 - interaction with chests and crafting tables.

**Comment by A5H73Y** [comment]
I appreciate that this fixed the initial problem, however I've gone for a different approach.
I've given the option to override the block place / break events so even ops can't do it.
As well as this, I've blocked all inventory opening (besides the player's inventory(which I suppose could also be blocked), using the below code.
Once again, thank you for your investigation and work involved for fixing this problem.
`@EventHandler
	public void onInventoryOpen(InventoryOpenEvent event) {
		if (!PlayerMethods.isPlaying(event.getPlayer().getName()))
			return;

		if (event.getInventory().getType() != InventoryType.PLAYER)
			event.setCancelled(true);
	}`

**Comment by steve4744** [comment]
No problem :-)
Sounds like a good approach.

**Pull request closed without merging**
